-- MySQL Script generated by MySQL Workbench
-- Fri Jan 15 00:20:06 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iweb_project_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iweb_project_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iweb_project_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `iweb_project_db` ;

-- -----------------------------------------------------
-- Table `iweb_project_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb_project_db`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `birth_day` DATETIME NULL COMMENT '',
  `age` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb_project_db`.`function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb_project_db`.`function` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `wording` VARCHAR(45) NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_function_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_function_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iweb_project_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb_project_db`.`training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb_project_db`.`training` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `year` VARCHAR(4) NOT NULL COMMENT '',
  `place` VARCHAR(45) NOT NULL COMMENT '',
  `diploma` VARCHAR(70) NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_training_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_training_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iweb_project_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb_project_db`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb_project_db`.`skill` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `wording` VARCHAR(45) NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_skill_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_skill_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iweb_project_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb_project_db`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb_project_db`.`project` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(100) NOT NULL COMMENT '',
  `description` VARCHAR(500) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb_project_db`.`user_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb_project_db`.`user_project` (
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `project_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`, `project_id`)  COMMENT '',
  INDEX `fk_user_has_project_project1_idx` (`project_id` ASC)  COMMENT '',
  INDEX `fk_user_has_project_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_has_project_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iweb_project_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `iweb_project_db`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb_project_db`.`university`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb_project_db`.`university` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `address` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb_project_db`.`laboratory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb_project_db`.`laboratory` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `descripition` VARCHAR(500) NULL COMMENT '',
  `university_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `university_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_laboratory_university1_idx` (`university_id` ASC)  COMMENT '',
  CONSTRAINT `fk_laboratory_university1`
    FOREIGN KEY (`university_id`)
    REFERENCES `iweb_project_db`.`university` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb_project_db`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb_project_db`.`team` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(500) NOT NULL COMMENT '',
  `laboratory_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `laboratory_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_team_laboratory1_idx` (`laboratory_id` ASC)  COMMENT '',
  CONSTRAINT `fk_team_laboratory1`
    FOREIGN KEY (`laboratory_id`)
    REFERENCES `iweb_project_db`.`laboratory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb_project_db`.`user_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb_project_db`.`user_team` (
  `team_id` INT UNSIGNED NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`team_id`, `user_id`)  COMMENT '',
  INDEX `fk_Team_has_user_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_Team_has_user_Team1_idx` (`team_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Team_has_user_Team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `iweb_project_db`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iweb_project_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
